services:
  - type: web
    name: my-service
    env: python
    pythonVersion: "3.11"
    buildCommand: >
      export CXXFLAGS="-std=c++17" &&
      pip install -r requirements.txt
    startCommand: python app.py
