



STANDARD_MAPPING = {
    "GLUCOSE": ["glucose", "glu", "sugar", "fbs", "rbs", "ppbs", "hba1c"],
    "CALCIUM": ["calcium", "ca", "mg", "phosphate"],
    "TOTAL_CHOLESTEROL": ["total cholesterol", "cholesterol", "tc", "tc m", "lipid", "lipoprotein"],
    "LDL": ["ldl", "ldl-c", "bad cholesterol"],
    "HDL": ["hdl", "hdl-c", "good cholesterol"],
    "VLDL": ["vldl", "vldl-c"],
    "TRIGLYCERIDES": ["triglycerides", "tg"],
    "UREA": ["urea", "bun", "ua"],
    "CREATININE": ["creatinine", "cr"],
    "URIC_ACID": ["uric acid", "ua"],
    "EGFR": ["egfr"],
    "ALT": ["alt", "sgpt"],
    "AST": ["ast", "sgot"],
    "ALP": ["alp"],
    "GGT": ["ggt"],
    "BILIRUBIN_TOTAL": ["bilirubin", "total bilirubin"],
    "BILIRUBIN_DIRECT": ["direct bilirubin"],
    "SODIUM": ["sodium", "na"],
    "POTASSIUM": ["potassium", "k"],
    "CHLORIDE": ["chloride", "cl"],
    "MAGNESIUM": ["magnesium", "mg"],
    "CBC": ["cbc", "wbc", "rbc", "hgb", "hemoglobin", "hct", "hematocrit", "mcv", "mch", "mchc", "plt", "platelets"],
    "CRP": ["crp", "hs-crp"],
    "ESR": ["esr"],
    "ANA": ["ana"],
    "RF": ["rf"],
    "PROCALCITONIN": ["procalcitonin"],
    "IGG": ["igg"],
    "IGM": ["igm"],
    "IGA": ["iga"],
    "TSH": ["tsh", "t3", "t4", "ft3", "ft4", "anti-tpo", "anti-tg"],
    "TESTOSTERONE": ["testosterone"],
    "ESTROGEN": ["estrogen"],
    "PROGESTERONE": ["progesterone"],
    "LH": ["lh"],
    "FSH": ["fsh"],
    "PROLACTIN": ["prolactin"],
    "INSULIN": ["insulin"],
    "VITAMIN_D": ["vitamin d", "vit d"],
    "VITAMIN_B12": ["vitamin b12", "b12"],
    "FOLATE": ["folate", "folic acid"],
    "URINE_ANALYSIS": ["urine", "stool", "albumin", "protein", "ketone", "bilirubin", "urobilinogen", "ph", "specific gravity", "pus cells", "rbc in urine"],
    "PSA": ["psa"],
    "CA_125": ["ca-125"],
    "CA19_9": ["ca19-9"],
    "CEA": ["cea"],
    "AFP": ["afp"],
    "CK": ["ck", "ck-mb"],
    "TROPONIN": ["troponin"],
    "LDH": ["ldh"],
    "MYOGLOBIN": ["myoglobin"],
    "BETA_HCG": ["beta hcg", "hcg"],
    "CO2": ["co2"],
    "ANION_GAP": ["anion gap"],
    "OSMOLARITY": ["osmolarity"],
    "LACTATE": ["lactate"],
    "AMYLASE": ["amylase"],
    "LIPASE": ["lipase"]
}
